# Generated by Django 3.0.8 on 2020-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_desc',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
